#!/usr/bin/env bash

set -e

FLAGS=""
FLAGS+=" --sysroot=${ESP_PATH}/xtensa-esp32-elf/sysroot"
FLAGS+=" -I${PROJECT}/build/include"
FLAGS+=" -D__bindgen"
FLAGS+=" -target xtensa"
FLAGS+=" -x c"

while read -r include; do
	FLAGS+=" -I${include}"
done <<< "$(find "${IDF_PATH}/components" -maxdepth 3 -name include)"

# Not picked up from above
FLAGS+=" -I${IDF_PATH}/components/lwip/lwip/src/include"
FLAGS+=" -I${IDF_PATH}/components/lwip/port/esp32/include"
FLAGS+=" -I${IDF_PATH}/components/newlib/platform_include"
FLAGS+=" -I${IDF_PATH}/components/lwip/include/apps"

: "${BINDGEN_FLAGS:=--use-core --no-layout-tests --ctypes-prefix=libc}"
: "${ESP32_SYS_DIR:=esp32-sys}"

cd "$ESP32_SYS_DIR"

#shellcheck disable=SC2086
bindgen $BINDGEN_FLAGS --output src/bindings.rs src/bindings.h -- $FLAGS
