#!/usr/bin/env bash

set -e

die() { echo "$*" 1>&2 ; exit 1 ; }

test -f Cargo.toml || die "unable to find 'Cargo.toml'. You will need to map the container path /home/project to the path of your Rust project. You can do this using: docker run -ti -v $PWD:/home/project/build:z rust-esp"

echo "Creating Makefile (Makefile)"
cp "${TEMPLATES}/Makefile" Makefile

echo "Creating esp-idf symlink (esp-idf -> /esp-idf)"
ln -sf "${IDF_PATH}" esp-idf

echo "Creating cargo config (.cargo/config)"
mkdir -p .cargo
cp "${TEMPLATES}/cargo.config" .cargo/config

echo "Creating main application wrapper (main/esp_app_main.c)"
mkdir -p main
cp "${TEMPLATES}/main.c" main/esp_app_main.c
cp "${TEMPLATES}/component.mk" main/

