#!/usr/bin/env bash

set -e

source "$IDF_PATH/export.sh"

"${IDF_PATH}/components/esptool_py/esptool/esptool.py" \
     --chip esp32 \
     elf2image \
     -o build/esp-app.bin \
     target/xtensa-esp32-none-elf/release/esp-app

echo "You can now flash 'build/esp-app.bin'"
