#!/usr/bin/env bash

set -e

$IDF_PATH/components/esptool_py/esptool/esptool.py --chip esp32 elf2image -o esp-app.bin target/xtensa-esp32-none-elf/release/esp-app

echo "You can now flash 'esp-app.bin'"
